services:
  - type: web
    name: fliphero-backend
    env: docker
    dockerfilePath: ./Dockerfile.backend
    healthCheckPath: /health
  
  - type: pserv
    name: fliphero-postgres
    env: docker
    plan: free 